version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  fastapi:
    image: 769744325574.dkr.ecr.us-east-1.amazonaws.com/fastapi:latest
    ports:
      - "8000:8000"
    environment:
      - TIMEOUT="300"
      - KEEP_ALIVE="300"
    container_name: fastapi
    volumes:
      - ./final_model.pth:/fastapi/models/final_model.pth
    networks:
      - mynetwork

  streamlit:
    image: 769744325574.dkr.ecr.us-east-1.amazonaws.com/streamlit:latest
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    container_name: streamlit
    environment:
      - FASTAPI_DOMAIN=fastapi
    networks:
      - mynetwork
