name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 769744325574.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        cd deploy_fastapi/streamlit && docker build -t 769744325574.dkr.ecr.us-east-1.amazonaws.com/streamlit:latest . && cd
        docker push 769744325574.dkr.ecr.us-east-1.amazonaws.com/streamlit:latest

  deploy-to-ecs:
    runs-on: ubuntu-latest

    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 769744325574.dkr.ecr.us-east-1.amazonaws.com

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster your-ecs-cluster-na

